### PR TITLE
fix: add path mapping rules to convert Windows paths to C4D's Linux path format

### LINKED ISSUE #118: Bug: Path mapping between a Windows scene and a Linux worker does not work as expected
### Describe the bug

The `c4d.RDATA_PATH` (output path) appear as a relative path on Linux when it is actually a Windows path.

For example:

*On Windows*: `P:\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png`
*On Linux*: `./P:/ahughes/_DeadlineCloudExamples/simple_c4d_naming_output/image.png`

The Linux path appears to be relative and therefore the `map_path` call returns a relative Linux path and the entire folder structure gets recreated relative to the scene file.

This causes additional issues because certain characters cannot be represented on Windows filesystems in paths (For example, the above path that the image.png gets written out to will be as follows `P:\ahughes\_DeadlineCloudExamples\P_\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png` because Windows turns the `P:` into `P_`)

### Expected Behaviour

I would expect Cinema4D to give us a non-relative path, but I guess we have to have the adaptor work around this and detect that the path is a relative Windows path and treat it as absolute?

### Current Behaviour

A relative path is returned and converted to Linux, so the entire filesystem is recreated from the scene_file
`P:\ahughes\_DeadlineCloudExamples\P_\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png` 

### Reproduction Steps

Create a scene in Windows Cinema4D and set the output path to be some absolute Windows path (I believe it converts it to absolute regardless) and then render the scene on a Linux Commandline worker.

Here is my modified plugin that you can use to just test the pathing:
```python
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
import os
import sys
import traceback

print('c4d python version: %s' % sys.version)
print('system paths:')
for n in sys.path:
    print(n)

import c4d

def setTake(take_name):
    doc = c4d.documents.GetActiveDocument()
    take_data = doc.GetTakeData()
    if not take_data:
        return

    def get_child_takes(take):
        child_takes = take.GetChildren()
        all_takes = child_takes
        if child_takes:
            for child_take in child_takes:
                all_takes.extend(get_child_takes(child_take))
        return all_takes

    main_take = take_data.GetCurrentTake()
    all_takes = [main_take] + get_child_takes(main_take)

    take = None
    for take in all_takes:
        if take.GetName() == take_name:
            break
    if take is None:
        print("Error: take not found: %s" % take_name)
    take_data.SetCurrentTake(take)


def parse_argv(argv):
    for arg in argv:
        if arg.find("-RdataTest") == 0:
            import c4d
            scene_file = "<PathToYourSceneFile>"
            print("Loading: {}".format(scene_file))
            doc = c4d.documents.LoadDocument(
                scene_file, c4d.SCENEFILTER_OBJECTS | c4d.SCENEFILTER_MATERIALS
            )
            c4d.documents.InsertBaseDocument(doc)
            c4d.documents.SetActiveDocument(doc)

            setTake("Main")

            doc = c4d.documents.GetActiveDocument()
            render_data = doc.GetActiveRenderData()
            print("RDATA_PATH: %s" % (render_data[c4d.RDATA_PATH]))
            return True
    return False


def PluginMessage(id, data):
    if id == c4d.C4DPL_COMMANDLINEARGS:
        return parse_argv(sys.argv)
    return False
```

### Environment

At minimum:
1. Operating system: Scene file created on Windows, Worker running RockyLinux9
2. Version of Cinema 4D: Cinema4D R26 on Windows Cinema4D 2024 on Linux
3: Version of this package: 0.5.4

Please share other details about your environment that you think might be relevant to reproducing the bug.

### PR DESCRIPTION
**Pull request by joel-wong-aws**
Fixes: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/issues/118

### What was the problem/requirement? (What/Why)
Jobs with assets that use absolute paths will fail due to missing assets

### What was the solution? (How)
This adds additional path mapping rules for Windows -> Linux in the form of `./C:\*` to allow paths to be mapped in the intended way. In conjunction with https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/pull/126 this applies path mapping to `RDATA_PATH`, `RDATA_MULTIPASS_FILENAME`, and all assets. 

### What is the impact of this change?
Absolute path references for assets now work on Linux!

### How was this change tested?
Submitted a physical render job (cube) with a texture that was mapped with an absolute path. It mapped the path correctly and succeeded the render!

- Have you run the unit tests?
Yes

### Did you run the "Job Bundle Output Tests"? If not, why not? If so, paste the test results here.
I ran the physical job bundle output test and a test for a physical cube with a texture. On my test instance, Redshift is not working for any scene.

### Was this change documented?
I added some in-code docstrings. We're still not confident enough to have official support for Linux, but both Physical and Redshift renders appear to be working on RedHat Linux types without GPUs. With GPUs, only physical renders have been working.

### Is this a breaking change?
No, this was an existing broken path before, so it would not have been part of a customer flow.

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

### CODE REVIEW

**Comment by Ahuge** [comment]
Nice work! 

Looking good!

**Review by crowecawcaw — APPROVED** [review]
Is there a way to unit test this?

**Review by karthikbekalp — APPROVED** [review]
Thanks for the fix!

**Comment by joel-wong-aws** [comment]
> Is there a way to unit test this?

Yes, I already have an action item to add more unit tests for the Cinema 4D integration. I'll add some tests for this as part of that.

**Pull request merged**
